'use client';

import '@/styles/global.css';
import '@mantine/core/styles.css';

import { MantineProvider } from '@mantine/core';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          {/* <Navbar />
          <Header /> */}
          {children}
        </MantineProvider>
      </body>
    </html>
  );
};

export default RootLayout;
